import type { Metadata } from "next";
import { DM_Mono, DM_Sans } from "next/font/google";
import { GoogleAnalytics } from "@next/third-parties/google";
import "./globals.css";

const dmSans = DM_Sans({
	variable: "--font-dm-sans",
	subsets: ["latin"],
});

const dmMono = DM_Mono({
	variable: "--font-dm-mono",
	subsets: ["latin"],
	weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
	title: "Ravix Studio",
	description: "Generated by create next app",
	appleWebApp: {
		title: "Ravix Studio",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const gaId = process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID;

	return (
		<html lang="en">
			<body
				className={`${dmSans.variable} ${dmMono.variable} antialiased overflow-x-hidden`}
			>
				{children}
			</body>
			{gaId && <GoogleAnalytics gaId={gaId} />}
		</html>
	);
}
